package model;
// Generated 2017/7/12 下午 05:20:31 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notes generated by hbm2java
 */
@Entity
@Table(name = "Notes", schema = "Meeting")
public class NotesBean implements java.io.Serializable {

	private Integer processId;
	private Date recordDate;
	private String sponsor;
	private String source;
	private String grade;
	private String discussMatter;
	private String presentation;
	private String reference;
	private String upload;
 
	public NotesBean() {
	}

	public NotesBean(Date recordDate, String sponsor, String source, String grade, String discussMatter,
			String presentation, String reference, String upload) {
		this.recordDate = recordDate;
		this.sponsor = sponsor;
		this.source = source;
		this.grade = grade;
		this.discussMatter = discussMatter;
		this.presentation = presentation;
		this.reference = reference;
		this.upload = upload;
	}

	 

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "process_id", unique = true, nullable = false)
	public Integer getProcessId() {
		return this.processId;
	}

	public void setProcessId(Integer processId) {
		this.processId = processId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "record_date", nullable = false, length = 10)
	public Date getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(Date recordDate) {
		this.recordDate = recordDate;
	}

	@Column(name = "sponsor", nullable = false, length = 32)
	public String getSponsor() {
		return this.sponsor;
	}

	public void setSponsor(String sponsor) {
		this.sponsor = sponsor;
	}

	@Column(name = "source", nullable = false, length = 800)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "grade", nullable = false, length = 3)
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	@Column(name = "discuss_matter", nullable = false, length = 3000)
	public String getDiscussMatter() {
		return this.discussMatter;
	}

	public void setDiscussMatter(String discussMatter) {
		this.discussMatter = discussMatter;
	}

	@Column(name = "presentation", nullable = false, length = 3000)
	public String getPresentation() {
		return this.presentation;
	}

	public void setPresentation(String presentation) {
		this.presentation = presentation;
	}

	@Column(name = "reference", nullable = false, length = 200)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "upload", nullable = false, length = 200)
	public String getUpload() {
		return this.upload;
	}

	public void setUpload(String upload) {
		this.upload = upload;
	}

	 
	@Override
	public String toString() {
		return "NotesBean [processId=" + processId + ", recordDate=" + recordDate + ", sponsor=" + sponsor + ", source="
				+ source + ", grade=" + grade + ", discussMatter=" + discussMatter + ", presentation=" + presentation
				+ ", reference=" + reference + ", upload=" + upload  + "]";
	}

}
