package model;
// Generated 2017/7/11 下午 06:01:35 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", catalog = "Meeting")
public class UserBean implements java.io.Serializable {

	private Integer id;
	private String user;
	private String passwd;
	private String chineseName;
	private String email;

	public UserBean() {
	}

	public UserBean(String user, String passwd, String chineseName, String email) {
		this.user = user;
		this.passwd = passwd;
		this.chineseName = chineseName;
		this.email = email;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user", nullable = false, length = 32)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "passwd", nullable = false, length = 32)
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	@Column(name = "ChineseName", nullable = false, length = 32)
	public String getChineseName() {
		return this.chineseName;
	}

	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	@Column(name = "email", nullable = false, length = 60)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public String toString() {
		return "UserBean [id=" + id + ", user=" + user + ", passwd=" + passwd + ", chineseName=" + chineseName
				+ ", email=" + email + "]";
	}

}
